In [22]:
Data <- read.csv(file="german_credit_data1.csv", header=TRUE, sep=",")

In [23]:
Data

     X.  Age Sex    Job Housing Saving.accounts Checking.account Credit.amount
1     0  67  male   2   own     NA              little            1169
2     1  22  female 2   own     little          moderate          5951
3     2  49  male   1   own     little          NA                2096
4     3  45  male   2   free    little          little            7882
5     4  53  male   2   free    little          little            4870
6     5  35  male   1   free    NA              NA                9055
7     6  53  male   2   own     quite rich      NA                2835
8     7  35  male   3   rent    little          moderate          6948
9     8  61  male   1   own     rich            NA                3059
10    9  28  male   3   own     little          moderate          5234
11   10  25  female 2   rent    little          moderate          1295
12   11  24  female 2   rent    little          little            4308
13   12  22  female 2   own     little          moderate          1567
14   13  60  male   1   own     little          little            1199
15   14  28  female 2   rent    little          little            1403
16   15  32  female 1   own     moderate        little            1282
17   16  53  male   2   own     NA              NA                2424
18   17  25  male   2   own     NA              little            8072
19   18  44  female 3   free    little          moderate         12579
20   19  31  male   2   own     quite rich      NA                3430
21   20  48  male   2   own     little          NA                2134
22   21  44  male   2   rent    quite rich      little            2647
23   22  48  male   1   rent    little          little            2241
24   23  44  male   2   own     moderate        moderate          1804
25   24  26  male   2   own     NA              NA                2069
26   25  36  male   1   own     little          little            1374
27   26  39  male   1   own     little          NA                 426
28   27  42  female 2   rent    rich            rich               409
29   28  34  male   2   own     little          moderate          2415
30   29  63  male   2   own     little          little            6836
⋮    ⋮   ⋮   ⋮      ⋮   ⋮       ⋮               ⋮                ⋮
971  970 22  male   2   own     moderate        moderate         1514
972  971 43  male   1   own     little          NA               7393
973  972 29  female 0   rent    little          little           1193
974  973 36  male   2   rent    little          little           7297
975  974 33  female 2   own     little          NA               2831
976  975 57  female 1   own     quite rich      rich             1258
977  976 64  female 2   own     little          moderate          753
978  977 42  male   2   own     NA              moderate         2427
979  978 47  male   1   own     little          NA               2538
980  979 25  male   2   rent    moderate        moderate         1264
981  980 49  male   2   own     little          moderate         8386
982  981 33  male   3   rent    little          NA               4844
983  982 28  female 3   own     moderate        rich             2923
984  983 26  male   2   own     little          little           8229
985  984 30  male   1   own     little          NA               2028
986  985 25  female 2   rent    little          little           1433
987  986 33  male   2   own     little          rich             6289
988  987 64  female 2   own     moderate        NA               1409
989  988 29  male   3   free    little          little           6579
990  989 48  male   1   own     little          moderate         1743
991  990 37  male   1   own     NA              NA               3565
992  991 34  male   1   own     moderate        NA               1569
993  992 23  male   1   rent    NA              little           1936
994  993 30  male   3   own     little          little           3959
995  994 50  male   2   own     NA              NA               2390
996  995 31  female 1   own     little          NA               1736
997  996 40  male   3   own     little          little           3857
998  997 38  male   2   own     little          NA                804
999  998 23  male   2   free    little          little           1845
1000 999 27  male   2   own     moderate        moderate         4576
     Duration Purpose             Credit.Risks
1     6       radio/TV            1
2    48       radio/TV            2
3    12       education           1
4    42       furniture/equipment 1
5    24       car                 2
6    36       education           1
7    24       furniture/equipment 1
8    36       car                 1
9    12       radio/TV            1
10   30       car                 2
11   12       car                 2
12   48       business            2
13   12       radio/TV            1
14   24       car                 2
15   15       car                 1
16   24       radio/TV            2
17   24       radio/TV            1
18   30       business            1
19   24       car                 2
20   24       radio/TV            1
21    9       car                 1
22    6       radio/TV            1
23   10       car                 1
24   12       car                 1
25   10       furniture/equipment 1
26    6       furniture/equipment 1
27    6       radio/TV            1
28   12       radio/TV            1
29    7       radio/TV            1
30   60       business            2
⋮    ⋮        ⋮                   ⋮
971  15       repairs             1
972  24       car                 1
973  24       car                 2
974  60       business            2
975  30       radio/TV            1
976  24       radio/TV            1
977   6       radio/TV            1
978  18       business            1
979  24       car                 2
980  15       car                 2
981  30       furniture/equipment 2
982  48       business            2
983  21       car                 1
984  36       car                 2
985  24       furniture/equipment 1
986  15       furniture/equipment 1
987  42       business            1
988  13       radio/TV            1
989  24       car                 1
990  24       radio/TV            1
991  12       education           1
992  15       radio/TV            1
993  18       radio/TV            1
994  36       furniture/equipment 1
995  12       car                 1
996  12       furniture/equipment 1
997  30       car                 1
998  12       radio/TV            1
999  45       radio/TV            2
1000 45       car                 1

In [24]:
str(Data)

'data.frame':	1000 obs. of  11 variables:
 $ X.              : int  0 1 2 3 4 5 6 7 8 9 ...
 $ Age             : int  67 22 49 45 53 35 53 35 61 28 ...
 $ Sex             : Factor w/ 2 levels "female","male": 2 1 2 2 2 2 2 2 2 2 ...
 $ Job             : int  2 2 1 2 2 1 2 3 1 3 ...
 $ Housing         : Factor w/ 3 levels "free","own","rent": 2 2 2 1 1 1 2 3 2 2 ...
 $ Saving.accounts : Factor w/ 4 levels "little","moderate",..: NA 1 1 1 1 NA 3 1 4 1 ...
 $ Checking.account: Factor w/ 3 levels "little","moderate",..: 1 2 NA 1 1 NA NA 2 NA 2 ...
 $ Credit.amount   : int  1169 5951 2096 7882 4870 9055 2835 6948 3059 5234 ...
 $ Duration        : int  6 48 12 42 24 36 24 36 12 30 ...
 $ Purpose         : Factor w/ 8 levels "business","car",..: 6 6 4 5 2 4 5 2 6 2 ...
 $ Credit.Risks    : int  1 2 1 1 2 1 1 1 1 2 ...

In [25]:
Data$Sex <- as.numeric(Data$Sex)
Data$Housing <- as.numeric(Data$Housing)
Data$Saving.accounts <- as.numeric(Data$Saving.accounts)
Data$Checking.account <- as.numeric(Data$Checking.account)
Data$Purpose <- as.numeric(Data$Purpose)

Converted character data to numeric so that it can be normalized

In [26]:
Data

     X.  Age Sex Job Housing Saving.accounts Checking.account Credit.amount
1     0  67  2   2   2       NA               1                1169
2     1  22  1   2   2        1               2                5951
3     2  49  2   1   2        1              NA                2096
4     3  45  2   2   1        1               1                7882
5     4  53  2   2   1        1               1                4870
6     5  35  2   1   1       NA              NA                9055
7     6  53  2   2   2        3              NA                2835
8     7  35  2   3   3        1               2                6948
9     8  61  2   1   2        4              NA                3059
10    9  28  2   3   2        1               2                5234
11   10  25  1   2   3        1               2                1295
12   11  24  1   2   3        1               1                4308
13   12  22  1   2   2        1               2                1567
14   13  60  2   1   2        1               1                1199
15   14  28  1   2   3        1               1                1403
16   15  32  1   1   2        2               1                1282
17   16  53  2   2   2       NA              NA                2424
18   17  25  2   2   2       NA               1                8072
19   18  44  1   3   1        1               2               12579
20   19  31  2   2   2        3              NA                3430
21   20  48  2   2   2        1              NA                2134
22   21  44  2   2   3        3               1                2647
23   22  48  2   1   3        1               1                2241
24   23  44  2   2   2        2               2                1804
25   24  26  2   2   2       NA              NA                2069
26   25  36  2   1   2        1               1                1374
27   26  39  2   1   2        1              NA                 426
28   27  42  1   2   3        4               3                 409
29   28  34  2   2   2        1               2                2415
30   29  63  2   2   2        1               1                6836
⋮    ⋮   ⋮   ⋮   ⋮   ⋮       ⋮               ⋮                ⋮
971  970 22  2   2   2        2               2               1514
972  971 43  2   1   2        1              NA               7393
973  972 29  1   0   3        1               1               1193
974  973 36  2   2   3        1               1               7297
975  974 33  1   2   2        1              NA               2831
976  975 57  1   1   2        3               3               1258
977  976 64  1   2   2        1               2                753
978  977 42  2   2   2       NA               2               2427
979  978 47  2   1   2        1              NA               2538
980  979 25  2   2   3        2               2               1264
981  980 49  2   2   2        1               2               8386
982  981 33  2   3   3        1              NA               4844
983  982 28  1   3   2        2               3               2923
984  983 26  2   2   2        1               1               8229
985  984 30  2   1   2        1              NA               2028
986  985 25  1   2   3        1               1               1433
987  986 33  2   2   2        1               3               6289
988  987 64  1   2   2        2              NA               1409
989  988 29  2   3   1        1               1               6579
990  989 48  2   1   2        1               2               1743
991  990 37  2   1   2       NA              NA               3565
992  991 34  2   1   2        2              NA               1569
993  992 23  2   1   3       NA               1               1936
994  993 30  2   3   2        1               1               3959
995  994 50  2   2   2       NA              NA               2390
996  995 31  1   1   2        1              NA               1736
997  996 40  2   3   2        1               1               3857
998  997 38  2   2   2        1              NA                804
999  998 23  2   2   1        1               1               1845
1000 999 27  2   2   2        2               2               4576
     Duration Purpose Credit.Risks
1     6       6       1
2    48       6       2
3    12       4       1
4    42       5       1
5    24       2       2
6    36       4       1
7    24       5       1
8    36       2       1
9    12       6       1
10   30       2       2
11   12       2       2
12   48       1       2
13   12       6       1
14   24       2       2
15   15       2       1
16   24       6       2
17   24       6       1
18   30       1       1
19   24       2       2
20   24       6       1
21    9       2       1
22    6       6       1
23   10       2       1
24   12       2       1
25   10       5       1
26    6       5       1
27    6       6       1
28   12       6       1
29    7       6       1
30   60       1       2
⋮    ⋮        ⋮       ⋮
971  15       7       1
972  24       2       1
973  24       2       2
974  60       1       2
975  30       6       1
976  24       6       1
977   6       6       1
978  18       1       1
979  24       2       2
980  15       2       2
981  30       5       2
982  48       1       2
983  21       2       1
984  36       2       2
985  24       5       1
986  15       5       1
987  42       1       1
988  13       6       1
989  24       2       1
990  24       6       1
991  12       4       1
992  15       6       1
993  18       6       1
994  36       5       1
995  12       2       1
996  12       5       1
997  30       2       1
998  12       6       1
999  45       6       2
1000 45       2       1

In [27]:
normalize <- function(x, na.rm = TRUE){
    ranx <- range(x, na.rm = na.rm)
    (x - ranx[1]) / diff(ranx)
}

Normalization function

In [28]:
mainFrame <- as.data.frame(lapply(Data[,c(1:10)], normalize))

Normalized columns 1 to 10 and stored in mainFrame

In [29]:
mainFrame

     X.          Age        Sex Job       Housing Saving.accounts
1    0.000000000 0.85714286 1   0.6666667 0.5            NA
2    0.001001001 0.05357143 0   0.6666667 0.5     0.0000000
3    0.002002002 0.53571429 1   0.3333333 0.5     0.0000000
4    0.003003003 0.46428571 1   0.6666667 0.0     0.0000000
5    0.004004004 0.60714286 1   0.6666667 0.0     0.0000000
6    0.005005005 0.28571429 1   0.3333333 0.0            NA
7    0.006006006 0.60714286 1   0.6666667 0.5     0.6666667
8    0.007007007 0.28571429 1   1.0000000 1.0     0.0000000
9    0.008008008 0.75000000 1   0.3333333 0.5     1.0000000
10   0.009009009 0.16071429 1   1.0000000 0.5     0.0000000
11   0.010010010 0.10714286 0   0.6666667 1.0     0.0000000
12   0.011011011 0.08928571 0   0.6666667 1.0     0.0000000
13   0.012012012 0.05357143 0   0.6666667 0.5     0.0000000
14   0.013013013 0.73214286 1   0.3333333 0.5     0.0000000
15   0.014014014 0.16071429 0   0.6666667 1.0     0.0000000
16   0.015015015 0.23214286 0   0.3333333 0.5     0.3333333
17   0.016016016 0.60714286 1   0.6666667 0.5            NA
18   0.017017017 0.10714286 1   0.6666667 0.5            NA
19   0.018018018 0.44642857 0   1.0000000 0.0     0.0000000
20   0.019019019 0.21428571 1   0.6666667 0.5     0.6666667
21   0.020020020 0.51785714 1   0.6666667 0.5     0.0000000
22   0.021021021 0.44642857 1   0.6666667 1.0     0.6666667
23   0.022022022 0.51785714 1   0.3333333 1.0     0.0000000
24   0.023023023 0.44642857 1   0.6666667 0.5     0.3333333
25   0.024024024 0.12500000 1   0.6666667 0.5            NA
26   0.025025025 0.30357143 1   0.3333333 0.5     0.0000000
27   0.026026026 0.35714286 1   0.3333333 0.5     0.0000000
28   0.027027027 0.41071429 0   0.6666667 1.0     1.0000000
29   0.028028028 0.26785714 1   0.6666667 0.5     0.0000000
30   0.029029029 0.78571429 1   0.6666667 0.5     0.0000000
⋮    ⋮           ⋮          ⋮   ⋮         ⋮       ⋮
971  0.970971    0.05357143 1   0.6666667 0.5     0.3333333
972  0.971972    0.42857143 1   0.3333333 0.5     0.0000000
973  0.972973    0.17857143 0   0.0000000 1.0     0.0000000
974  0.973974    0.30357143 1   0.6666667 1.0     0.0000000
975  0.974975    0.25000000 0   0.6666667 0.5     0.0000000
976  0.975976    0.67857143 0   0.3333333 0.5     0.6666667
977  0.976977    0.80357143 0   0.6666667 0.5     0.0000000
978  0.977978    0.41071429 1   0.6666667 0.5            NA
979  0.978979    0.50000000 1   0.3333333 0.5     0.0000000
980  0.979980    0.10714286 1   0.6666667 1.0     0.3333333
981  0.980981    0.53571429 1   0.6666667 0.5     0.0000000
982  0.981982    0.25000000 1   1.0000000 1.0     0.0000000
983  0.982983    0.16071429 0   1.0000000 0.5     0.3333333
984  0.983984    0.12500000 1   0.6666667 0.5     0.0000000
985  0.984985    0.19642857 1   0.3333333 0.5     0.0000000
986  0.985986    0.10714286 0   0.6666667 1.0     0.0000000
987  0.986987    0.25000000 1   0.6666667 0.5     0.0000000
988  0.987988    0.80357143 0   0.6666667 0.5     0.3333333
989  0.988989    0.17857143 1   1.0000000 0.0     0.0000000
990  0.989990    0.51785714 1   0.3333333 0.5     0.0000000
991  0.990991    0.32142857 1   0.3333333 0.5            NA
992  0.991992    0.26785714 1   0.3333333 0.5     0.3333333
993  0.992993    0.07142857 1   0.3333333 1.0            NA
994  0.993994    0.19642857 1   1.0000000 0.5     0.0000000
995  0.994995    0.55357143 1   0.6666667 0.5            NA
996  0.995996    0.21428571 0   0.3333333 0.5     0.0000000
997  0.996997    0.37500000 1   1.0000000 0.5     0.0000000
998  0.997998    0.33928571 1   0.6666667 0.5     0.0000000
999  0.998999    0.07142857 1   0.6666667 0.0     0.0000000
1000 1.000000    0.14285714 1   0.6666667 0.5     0.3333333
     Checking.account Credit.amount Duration   Purpose
1    0.0              0.050566744   0.02941176 0.7142857
2    0.5              0.313689887   0.64705882 0.7142857
3     NA              0.101573677   0.11764706 0.4285714
4    0.0              0.419940574   0.55882353 0.5714286
5    0.0              0.254209310   0.29411765 0.1428571
6     NA              0.484483328   0.47058824 0.4285714
7     NA              0.142236162   0.29411765 0.5714286
8    0.5              0.368548476   0.47058824 0.1428571
9     NA              0.154561461   0.11764706 0.7142857
10   0.5              0.274237922   0.38235294 0.1428571
11   0.5              0.057499725   0.11764706 0.1428571
12   0.0              0.223286013   0.64705882 0.0000000
13   0.5              0.072466160   0.11764706 0.7142857
14   0.0              0.052217454   0.29411765 0.1428571
15   0.0              0.063442280   0.16176471 0.1428571
16   0.0              0.056784417   0.29411765 0.7142857
17    NA              0.119621437   0.29411765 0.7142857
18   0.0              0.430395070   0.38235294 0.0000000
19   0.5              0.678386706   0.29411765 0.1428571
20    NA              0.174975239   0.29411765 0.7142857
21    NA              0.103664576   0.07352941 0.1428571
22   0.0              0.131891713   0.02941176 0.7142857
23   0.0              0.109552107   0.08823529 0.1428571
24   0.5              0.085506768   0.11764706 0.1428571
25    NA              0.100088038   0.08823529 0.5714286
26   0.0              0.061846594   0.02941176 0.5714286
27    NA              0.009684164   0.02941176 0.7142857
28   1.0              0.008748762   0.11764706 0.7142857
29   0.5              0.119126224   0.04411765 0.7142857
30   0.0              0.362385826   0.82352941 0.0000000
⋮    ⋮                ⋮             ⋮          ⋮
971  0.5              0.06954991    0.16176471 0.8571429
972   NA              0.39303400    0.29411765 0.1428571
973  0.0              0.05188731    0.29411765 0.1428571
974  0.0              0.38775173    0.82352941 0.0000000
975   NA              0.14201607    0.38235294 0.7142857
976  1.0              0.05546385    0.29411765 0.7142857
977  0.5              0.02767690    0.02941176 0.7142857
978  0.5              0.11978651    0.20588235 0.0000000
979   NA              0.12589413    0.29411765 0.1428571
980  0.5              0.05579399    0.16176471 0.1428571
981  0.5              0.44767250    0.38235294 0.5714286
982   NA              0.25277869    0.64705882 0.0000000
983  1.0              0.14707824    0.25000000 0.1428571
984  0.0              0.43903378    0.47058824 0.1428571
985   NA              0.09783207    0.29411765 0.5714286
986  0.0              0.06509299    0.16176471 0.5714286
987  1.0              0.33228788    0.55882353 0.0000000
988   NA              0.06377242    0.13235294 0.7142857
989  0.0              0.34824475    0.29411765 0.1428571
990  0.5              0.08215032    0.29411765 0.7142857
991   NA              0.18240343    0.11764706 0.4285714
992   NA              0.07257621    0.16176471 0.7142857
993  0.0              0.09276989    0.20588235 0.7142857
994  0.0              0.20408276    0.47058824 0.5714286
995   NA              0.11775063    0.11764706 0.1428571
996   NA              0.08176516    0.11764706 0.5714286
997  0.0              0.19847034    0.38235294 0.1428571
998   NA              0.03048311    0.11764706 0.7142857
999  0.0              0.08776274    0.60294118 0.7142857
1000 0.5              0.23803235    0.60294118 0.1428571

In [30]:
str(mainFrame)

'data.frame':	1000 obs. of  10 variables:
 $ X.              : num  0 0.001 0.002 0.003 0.004 ...
 $ Age             : num  0.8571 0.0536 0.5357 0.4643 0.6071 ...
 $ Sex             : num  1 0 1 1 1 1 1 1 1 1 ...
 $ Job             : num  0.667 0.667 0.333 0.667 0.667 ...
 $ Housing         : num  0.5 0.5 0.5 0 0 0 0.5 1 0.5 0.5 ...
 $ Saving.accounts : num  NA 0 0 0 0 ...
 $ Checking.account: num  0 0.5 NA 0 0 NA NA 0.5 NA 0.5 ...
 $ Credit.amount   : num  0.0506 0.3137 0.1016 0.4199 0.2542 ...
 $ Duration        : num  0.0294 0.6471 0.1176 0.5588 0.2941 ...
 $ Purpose         : num  0.714 0.714 0.429 0.571 0.143 ...

In [31]:
summary(mainFrame)

       X.            Age              Sex            Job
 Min.   :0.00   Min.   :0.0000   Min.   :0.00   Min.   :0.0000
 1st Qu.:0.25   1st Qu.:0.1429   1st Qu.:0.00   1st Qu.:0.6667
 Median :0.50   Median :0.2500   Median :1.00   Median :0.6667
 Mean   :0.50   Mean   :0.2955   Mean   :0.69   Mean   :0.6347
 3rd Qu.:0.75   3rd Qu.:0.4107   3rd Qu.:1.00   3rd Qu.:0.6667
 Max.   :1.00   Max.   :1.0000   Max.   :1.00   Max.   :1.0000

    Housing       Saving.accounts  Checking.account Credit.amount
 Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.00000
 1st Qu.:0.5000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.06138
 Median :0.5000   Median :0.0000   Median :0.5000   Median :0.11387
 Mean   :0.5355   Mean   :0.1522   Mean   :0.3259   Mean   :0.16624
 3rd Qu.:0.5000   3rd Qu.:0.3333   3rd Qu.:0.5000   3rd Qu.:0.20481
 Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.00000
                  NA's   :183      NA's   :394
    Duration         Purpose
 Min.   :0.0000   Min.   :0.0000
 1st Qu.:0.1176   1st Qu.:0.1429
 Median :0.2059   Median :0.4286
 Mean   :0.2486   Mean   :0.4111
 3rd Qu.:0.2941   3rd Qu.:0.7143
 Max.   :1.0000   Max.   :1.0000

In [32]:
newData <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20)
newData <- data.frame(newData)

In [42]:
set.seed(9850)
rand <- runif(nrow(mainFrame))
mainFrame <- mainFrame[order(rand),]

set.seed(9850)
rand <- runif(nrow(Data))
Data <- Data[order(rand),]

Frame_train <- mainFrame[1:900, ]
Frame_test <- mainFrame[901:1000, ]
Frame_train_target <- Data[1:900, 11]
Frame_test_target <- Data[901:1000, 11]

1. Created train,test and target data frames
2. Each time we are randomly sampling the data
3. We also need to vary the training and test sets manually. In this case the train/test ratio is 9:1

In [43]:
Frame_train$Saving.accounts[is.na(Frame_train$Saving.accounts)] <- 0
Frame_train$Checking.account[is.na(Frame_train$Checking.account)] <- 0
Frame_test$Saving.accounts[is.na(Frame_test$Saving.accounts)] <- 0
Frame_test$Checking.account[is.na(Frame_test$Checking.account)] <- 0

1. Converted all NA values to 0

In [44]:
require(class)
k = c()
for (i in 1:20){
      model <- knn(train = Frame_train, test = Frame_test, cl = Frame_train_target, k = i) #Actual knn classification
      tab <- table(Frame_test_target, model)
      k[i] <- 1-sum(diag(tab))/sum(tab)
}
newData <- cbind(newData,k)
newData

   newData k      k         k     k
1   1      0.3775 0.3633333 0.410 0.34
2   2      0.3650 0.3633333 0.400 0.40
3   3      0.3450 0.3700000 0.385 0.29
4   4      0.3650 0.3500000 0.380 0.35
5   5      0.3700 0.3466667 0.370 0.29
6   6      0.3250 0.3466667 0.375 0.35
7   7      0.3275 0.3100000 0.385 0.32
8   8      0.3025 0.3233333 0.360 0.33
9   9      0.3100 0.3066667 0.335 0.30
10 10      0.3125 0.2966667 0.305 0.33
11 11      0.3025 0.3066667 0.320 0.31
12 12      0.3100 0.3000000 0.325 0.31
13 13      0.3050 0.2866667 0.320 0.34
14 14      0.3200 0.2933333 0.295 0.34
15 15      0.3200 0.3000000 0.305 0.34
16 16      0.3125 0.2900000 0.330 0.34
17 17      0.3075 0.3000000 0.320 0.32
18 18      0.2950 0.2966667 0.315 0.33
19 19      0.2950 0.3100000 0.310 0.33
20 20      0.3050 0.3100000 0.305 0.32

1. Actual KNN implementation by running a for loop for all values of k ranging from 1 to 20
2. We do this 4 times for 60, 70 , 80 and 90% of training data

In [45]:
Final <- newData
names(Final) <- c("k","train=60%","train=70%","train=80%","train=90%")
Final

   k  train=60% train=70% train=80% train=90%
1   1 0.3775    0.3633333 0.410     0.34
2   2 0.3650    0.3633333 0.400     0.40
3   3 0.3450    0.3700000 0.385     0.29
4   4 0.3650    0.3500000 0.380     0.35
5   5 0.3700    0.3466667 0.370     0.29
6   6 0.3250    0.3466667 0.375     0.35
7   7 0.3275    0.3100000 0.385     0.32
8   8 0.3025    0.3233333 0.360     0.33
9   9 0.3100    0.3066667 0.335     0.30
10 10 0.3125    0.2966667 0.305     0.33
11 11 0.3025    0.3066667 0.320     0.31
12 12 0.3100    0.3000000 0.325     0.31
13 13 0.3050    0.2866667 0.320     0.34
14 14 0.3200    0.2933333 0.295     0.34
15 15 0.3200    0.3000000 0.305     0.34
16 16 0.3125    0.2900000 0.330     0.34
17 17 0.3075    0.3000000 0.320     0.32
18 18 0.2950    0.2966667 0.315     0.33
19 19 0.2950    0.3100000 0.310     0.33
20 20 0.3050    0.3100000 0.305     0.32

The misclassification rates are shown in the table above

# ----------------------------------------------------------------------------------------------------------------